name: MoveyAPI
version: '${project.version}'
main: dev.tom.moveyapi.MoveyAPI
api-version: '1.20'
commands:
  addblock:
    description: Add a block to the database
    usage: /<command> <block> <price>
  test:
    description: Test command
    usage: /<command>
